### ISSUE TITLE
Add build process

### ISSUE THREAD

**Issue by XiBOR** [Cyclonelabs/framework#12]
First step, main file (oakwood.scss) compile to some temporary css file.
Step two, apply postcss's modules (nsBuilder and Autoprefixer) to compiled file.
Step three, put compiled file to /compiled/oakwood.css
Last step, apply postcss's module to compress to file /compiled/oakwood.min.css

Links:
[Autoprefixer](https://github.com/postcss/autoprefixer)
[nsBuilder](https://github.com/XiBOR/css.framework/tree/master/PostCSS)
[postcss-CLI](https://www.npmjs.com/package/postcss-cli)

**Comment by XiBOR** [comment]
if you know better name for this folder, please use it
compiled was just example

**Comment by justVitalius** [comment]
@XiBOR what about font-files? Are there necessarily to copy fonts to <compiled> folder?

**Comment by XiBOR** [comment]
Look tasks #16
